In [11]:
import pandas as pd

exam_data = {
    '이름': ['서준', '우현', '인아'],
    '수학': [90, 80, 70],
    '영어': [98, 89, 95],
    '음악': [95, 95, 100],
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [4]:
print(df.ndim)
print(df.shape)

2
(3, 5)

In [12]:
ndf = df.set_index('이름')
ndf

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [13]:
ndf2 = ndf.set_index('음악')
ndf2

     수학  영어   체육
음악
95   90  98  100
95   80  89   90
100  70  95   90

In [14]:
ndf3 = ndf.set_index(['수학', '음악'])
ndf3

        영어   체육
수학 음악
90 95   98  100
80 95   89   90
70 100  95   90

In [17]:
# 행 인덱스 재배열

import pandas as pd

dict_data = {
    "c0": [1, 2, 3],
    'c1': [4, 5, 6],
    'c2': [7, 8, 9],
    'c3': [10, 11, 12],
    'c4': [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [20]:
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf = df.reindex(new_index)
ndf

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [29]:
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
ndf2 = df.reindex(new_index, fill_value='')
ndf2

   c0 c1 c2  c3  c4
r0  1  4  7  10  13
r1  2  5  8  11  14
r2  3  6  9  12  15
r3
r4

In [1]:
# 행 인덱스 초기화
## df객체.reset_index()

import pandas as pd

dict_data = {
    "c0": [1, 2, 3],
    'c1': [4, 5, 6],
    'c2': [7, 8, 9],
    'c3': [10, 11, 12],
    'c4': [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])

print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [2]:
ndf = df.reset_index()
print(df)
print(ndf)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [3]:
ndf2 = df.reset_index(names = ['c00'])
print(ndf2)

  c00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [4]:
ndf3 = df.reset_index(drop = True)
ndf3

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [17]:
# 행 인덱스를 기준으로 데이터프레임 정렬
## df객체.sort_index()

import pandas as pd

dict_data = {
    "c0": [1, 2, 3],
    'c1': [4, 5, 6],
    'c2': [7, 8, 9],
    'c3': [10, 11, 12],
    'c4': [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=['r0', 'r2', 'r1'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15

In [12]:
print(df.sort_index())
print(df)
ndf = df.sort_index()
ndf

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r2   2   5   8  11  14
r1   3   6   9  12  15

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   3   6   9  12  15
r2   2   5   8  11  14

In [18]:
ndf2 = df.sort_index(ascending=False)
ndf2

    c0  c1  c2  c3  c4
r2   2   5   8  11  14
r1   3   6   9  12  15
r0   1   4   7  10  13

In [21]:
# 열 기준 정렬
## df객체.sort_values()

import pandas as pd

dict_data = {
    "c0": [1, 2, 3],
    'c1': [4, 5, 6],
    'c2': [7, 8, 9],
    'c3': [10, 11, 12],
    'c4': [13, 14, 15]
}

df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [23]:
ndf = df.sort_values("c2")
ndf

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [25]:
ndf2 = df.sort_values("c2", ascending = False)
ndf2

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [27]:
ndf4 = df.sort_values(by = ['c3', 'c4'], ascending=[False, True])
ndf4

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13