In [11]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")

# 행 인덱스 0~9 범위에서 age, fare 2개열을 선택하여 데이터프레임 만들기

df = titanic.loc[0:9, ['age', 'fare']]

df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [13]:
# 불린 인덱싱(boolean indexing)

# 조건식 적용 (20세 미만, age < 20)

df['age'] < 20

# 불린 인덱싱(20세 미만의 조건을 충족하는 행을 필터링)

cond = df['age'] < 20
df[cond]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [14]:
df.loc[cond]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [28]:
maks1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[maks1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [36]:
# 나이가 10세미만이고 여성인 승객

mask2 = (titanic.age < 10) & (titanic.sex == 'female')
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [51]:
mask3 =  (titanic.age < 10) |  (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3,['age', 'sex', 'alone']]
df_under10_morethan60

       age     sex  alone
7     2.00    male  False
10    4.00  female  False
16    2.00    male  False
24    8.00  female  False
33   66.00    male   True
..     ...     ...    ...
831   0.83    male  False
850   4.00    male  False
851  74.00    male   True
852   9.00  female  False
869   4.00    male  False

[88 rows x 3 columns]

In [57]:
# query() 메서드 활용

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")

# 행 인덱스 0~9 범위에서 age, fare 2개열을 선택하여 데이터프레임 만들기

df = titanic.loc[ : , ['age', 'fare']]

df

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [58]:
# 20세 미만의 조건을 충족하는 행을 필터링

df.query('age < 20')

      age     fare
7     2.0  21.0750
9    14.0  30.0708
10    4.0  16.7000
14   14.0   7.8542
16    2.0  29.1250
..    ...      ...
855  18.0   9.3500
869   4.0  11.1333
875  15.0   7.2250
877  19.0   7.8958
887  19.0  30.0000

[164 rows x 2 columns]

In [60]:
# 20세 이상이고 요금이 15미만인 조건을 모두 충족하는 행을 필터링

df.query("age >= 20 and fare < 15")

      age     fare
0    22.0   7.2500
2    26.0   7.9250
4    35.0   8.0500
8    27.0  11.1333
12   20.0   8.0500
..    ...      ...
882  22.0  10.5167
883  28.0  10.5000
884  25.0   7.0500
886  27.0  13.0000
890  32.0   7.7500

[279 rows x 2 columns]

In [62]:
df.query("age >= 20 or fare < 15")

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
889  26.0  30.0000
890  32.0   7.7500

[728 rows x 2 columns]

In [74]:
# isin() 메서드 활용

## df객체.isin(추출 값의 리스트)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")

pd.set_option("display.max_columns", 10)

mask1 = titanic['embark_town'] == 'Southampton'
mask2 = titanic['embark_town'] == 'Queenstown'

df_boolean = titanic[mask1 | mask2]
df_boolean.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True

In [76]:
isin_filter = titanic['embark_town'].isin(['Southampton', 'Queenstown'])
df_isin = titanic[isin_filter]
df_isin.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True