In [ ]:
# 문자열을 timestamp로 변환

import pandas as pd

df = pd.read_csv("./data/stock-data.csv")
df['new_Date'] = pd.to_datetime(df['Date'])
df.head()

In [ ]:
df.info()

In [ ]:

df.head(5)

In [ ]:
df.info()

In [ ]:
df = df.set_index('new_Date')

df.head()

In [ ]:
df = df.drop("Date", axis=1)
df.head()

In [ ]:
pd.DatetimeIndex(["2022-12-25", "2023/01/25"])

In [2]:
# pd.DatetimeIndex(["2022:12:25", "2023|01|25"])

In [10]:
pd.to_datetime("2023년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2023-12-25 00:00:00')

In [13]:
pd.to_datetime("12-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2023-12-12 23:59:59')

In [16]:
pd.to_datetime("2022:12:25", format="%Y:%m:%d")

Timestamp('2022-12-25 00:00:00')

In [17]:
# period

import pandas as pd

dates = ['2019-01-01', '2020-03-01', '2020-06-01']

ts_dates = pd.to_datetime(dates)

ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2020-06-01'], dtype='datetime64[us]', freq=None)

In [18]:
pr_day = ts_dates.to_period(freq="D")
pr_month = ts_dates.to_period(freq="M")
pr_year = ts_dates.to_period(freq="Y")

print(pr_day)
print(pr_month)
print(pr_year)

PeriodIndex(['2019-01-01', '2020-03-01', '2020-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2020-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2020'], dtype='period[Y-DEC]')

In [19]:
df

            Close  Start   High    Low  Volume
new_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039
2018-06-25  11150  11400  11450  11000   55519
2018-06-22  11300  11250  11450  10750  134805
2018-06-21  11200  11350  11750  11200  133002
2018-06-20  11550  11200  11600  10900  308596
2018-06-19  11300  11850  11950  11300  180656
2018-06-18  12000  13400  13400  12000  309787
2018-06-15  13400  13600  13600  12900  201376
2018-06-14  13450  13200  13700  13150  347451
2018-06-12  13200  12200  13300  12050  558148
2018-06-11  11950  12000  12250  11950   62293
2018-06-08  11950  11950  12200  11800   59258
2018-06-07  11950  12200  12300  11900   49088
2018-06-05  12150  11800  12250  11800   42485
2018-06-04  11900  11900  12200  11700   25171
2018-06-01  11900  11800  12100  11750   32062

In [21]:
# 시계열 데이터 만들기
ts_ms = pd.date_range(
    start="2024-01-01", 
    end=None, 
    periods=6, 
    freq="MS",
    tz='Asia/Seoul'
)
print(ts_ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [22]:
ts_ms = pd.date_range(
    start="2024-01-01", 
    end=None, 
    periods=6, 
    freq="ME",
    tz='Asia/Seoul'
)
print(ts_ms)

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [23]:
ts_ms = pd.date_range(
    start="2024-01-01", 
    end=None, 
    periods=6, 
    freq="3MS",
    tz='Asia/Seoul'
)
print(ts_ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [26]:
pr_m = pd.period_range(
    start="2024-01-01", 
    end=None, 
    periods=3, 
    freq="M"
)

pr_m

PeriodIndex(['2024-01', '2024-02', '2024-03'], dtype='period[M]')

In [27]:
# 시계열 데이터 활용
## 날짜 데이터 분리

df = pd.read_csv("./data/stock-data.csv")
df['new_Date'] = pd.to_datetime(df['Date'])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [29]:
df["new_Date"].dt.year.head()

0    2018
1    2018
2    2018
3    2018
4    2018
Name: new_Date, dtype: int32

In [31]:
df['Date'].str[0:4].head()

0    2018
1    2018
2    2018
3    2018
4    2018
Name: Date, dtype: str

In [32]:
df['Date'][0:4].head()

0    2018-07-02
1    2018-06-29
2    2018-06-28
3    2018-06-27
Name: Date, dtype: str

In [33]:
df["new_Date"].dt.year
df["new_Date"].dt.month
df["new_Date"].dt.day

0      2
1     29
2     28
3     27
4     26
5     25
6     22
7     21
8     20
9     19
10    18
11    15
12    14
13    12
14    11
15     8
16     7
17     5
18     4
19     1
Name: new_Date, dtype: int32

In [34]:
df['Date_m'] = df['new_Date'].dt.to_period(freq="M")
df.head()

         Date  Close  Start   High    Low  Volume   new_Date   Date_m
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018-07
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018-06
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018-06
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018-06
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018-06

In [35]:
# 시간 인덱스 활용 

df = df.set_index('new_Date').sort_index()

df.head(10)

                  Date  Close  Start   High    Low  Volume   Date_m
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062  2018-06
2018-06-04  2018-06-04  11900  11900  12200  11700   25171  2018-06
2018-06-05  2018-06-05  12150  11800  12250  11800   42485  2018-06
2018-06-07  2018-06-07  11950  12200  12300  11900   49088  2018-06
2018-06-08  2018-06-08  11950  11950  12200  11800   59258  2018-06
2018-06-11  2018-06-11  11950  12000  12250  11950   62293  2018-06
2018-06-12  2018-06-12  13200  12200  13300  12050  558148  2018-06
2018-06-14  2018-06-14  13450  13200  13700  13150  347451  2018-06
2018-06-15  2018-06-15  13400  13600  13600  12900  201376  2018-06
2018-06-18  2018-06-18  12000  13400  13400  12000  309787  2018-06

In [36]:
df.loc['2018-06-27']

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Date_m       2018-06
Name: 2018-06-27 00:00:00, dtype: object

In [37]:
df.loc['2018-06-27': '2018-07-02']

                  Date  Close  Start   High    Low  Volume   Date_m
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548  2018-06
2018-06-28  2018-06-28  10400  10900  10950  10150  155769  2018-06
2018-06-29  2018-06-29  10700  10550  10900   9990  170253  2018-06
2018-07-02  2018-07-02  10100  10850  10900  10000  137977  2018-07

In [40]:
df[df.index < '2018-06-05']

                  Date  Close  Start   High    Low  Volume   Date_m
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062  2018-06
2018-06-04  2018-06-04  11900  11900  12200  11700   25171  2018-06

In [42]:
df = df.drop('Date', axis=1)

In [44]:
ts = df.head(10)

In [45]:
ts.shift(1)

              Close    Start     High      Low    Volume   Date_m
new_Date
2018-06-01      NaN      NaN      NaN      NaN       NaN      NaT
2018-06-04  11900.0  11800.0  12100.0  11750.0   32062.0  2018-06
2018-06-05  11900.0  11900.0  12200.0  11700.0   25171.0  2018-06
2018-06-07  12150.0  11800.0  12250.0  11800.0   42485.0  2018-06
2018-06-08  11950.0  12200.0  12300.0  11900.0   49088.0  2018-06
2018-06-11  11950.0  11950.0  12200.0  11800.0   59258.0  2018-06
2018-06-12  11950.0  12000.0  12250.0  11950.0   62293.0  2018-06
2018-06-14  13200.0  12200.0  13300.0  12050.0  558148.0  2018-06
2018-06-15  13450.0  13200.0  13700.0  13150.0  347451.0  2018-06
2018-06-18  13400.0  13600.0  13600.0  12900.0  201376.0  2018-06

In [47]:
ts.shift(-2)

              Close    Start     High      Low    Volume   Date_m
new_Date
2018-06-01  12150.0  11800.0  12250.0  11800.0   42485.0  2018-06
2018-06-04  11950.0  12200.0  12300.0  11900.0   49088.0  2018-06
2018-06-05  11950.0  11950.0  12200.0  11800.0   59258.0  2018-06
2018-06-07  11950.0  12000.0  12250.0  11950.0   62293.0  2018-06
2018-06-08  13200.0  12200.0  13300.0  12050.0  558148.0  2018-06
2018-06-11  13450.0  13200.0  13700.0  13150.0  347451.0  2018-06
2018-06-12  13400.0  13600.0  13600.0  12900.0  201376.0  2018-06
2018-06-14  12000.0  13400.0  13400.0  12000.0  309787.0  2018-06
2018-06-15      NaN      NaN      NaN      NaN       NaN      NaT
2018-06-18      NaN      NaN      NaN      NaN       NaN      NaT

In [ ]:
#추가로 머신러닝을 학습하기