In [17]:
# 문자열을 timestamp로 변환

import pandas as pd 

df = pd.read_csv('./data/stock-data.csv')

print(df.head())
print()
print(df.info())

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB
None

In [18]:
df['New_Date'] = pd.to_datetime(df['Date'])
df.head()

         Date  Close  Start   High    Low  Volume   New_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [19]:
df = df.set_index('New_Date')
df.head()

                  Date  Close  Start   High    Low  Volume
New_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [20]:
df = df.drop("Date", axis = 1)
df.head()

            Close  Start   High    Low  Volume
New_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [21]:
pd.DatetimeIndex(["2022-12-25", "2023/01/25"])

DatetimeIndex(['2022-12-25', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [34]:
# 문자열 포맷

pd.to_datetime("2023년 12월 25일 23:59:59", format="%Y년 %m월 %d일 %H:%M:%S")

Timestamp('2023-12-25 23:59:59')

In [38]:
pd.to_datetime("25-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2023-12-25 23:59:59')

In [40]:
# period

import pandas as pd

dates = ['2019-01-01', '2020-03-01', '2021-06-01']

ts_dates = pd.to_datetime(dates)
print(ts_dates)

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [42]:
pr_day=ts_dates.to_period(freq='D')
print(pr_day)
pr_month=ts_dates.to_period(freq='M')
print(pr_month)
pr_year=ts_dates.to_period(freq='Y')
print(pr_year)

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')
PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')
PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [44]:
# 시계열 데이터 만들기

ts_ms = pd.date_range(
                start = '2024-01-01',
                end=None,
                periods=6,
                freq='MS',
                tz='Asia/Seoul'
                )

print(ts_ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [49]:
ts_2ms = pd.date_range(
                start = '2024-01-01',
                end=None,
                periods=6,
                freq='ME',
                tz='Asia/Seoul'
                )

print(ts_2ms)

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [48]:
ts_3ms = pd.date_range(
                start = '2024-01-01',
                end=None,
                periods=6,
                freq='3MS',
                tz='Asia/Seoul'
                )

print(ts_3ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [51]:
pr_m = ts_ms = pd.period_range(
                start = '2024-01-01',
                end=None,
                periods=3,
                freq='M',
                )

print(pr_m)

PeriodIndex(['2024-01', '2024-02', '2024-03'], dtype='period[M]')

In [52]:
# 시계열 데이터 활용
# 날짜 데이터 분리

df = pd.rea

AttributeError: module 'pandas' has no attribute 'rea'

In [ ]:
df['Date_M']

In [54]:
# 시간 인덱스 활용

# df.set_index('New_Date')